# Déclaration des événements pour NGINX
events {
    worker_connections 1024; # Nombre maximum de connexions simultanées par worker
}
http {
    server {
        listen 80; # NGINX écoute sur le port 80
        server_name localhost; # Nom du serveur pour l'environnement local
        # Route interne pour valider le token JWT
        location /authenticate {
            internal; # Accessible uniquement depuis NGINX, pas depuis l'extérieur
            proxy_pass_request_body off; # Ne pas transmettre le corps de la requête
            proxy_set_header Content-Length ""; # En-tête nécessaire car on ne transmet pas le body
            proxy_set_header X-Original-URI $request_uri; # Conserver l'URI originale pour logging ou suivi
            # Redirection vers le service d'authentification pour validation du token
            proxy_pass http://auth-service:3000/api/auth/validate;
        }
        # Route publique pour le login
        location /login {
            proxy_pass http://auth-service:3000/api/auth/login; 
        }
        # Route publique pour l'enregistrement
        location /register {
            proxy_pass http://auth-service:3000/api/auth/register;
        }
        location /private {
            auth_request /authenticate;
            proxy_pass http://private-service:3000/api/;
        }
    }
}